# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f841cc0972f2b6745102ca3f044891f2ee503372a0e12c22bd41746fa70caf9a77c7a25a70e28376bb914b284114e3955a9ddb711ebbd1c509b0cd803de4e3

test:
  secret_key_base: 2b2b7b36cc56de394016c7c235f1d03e49fd16ca7a33fdfbe7bf51548704af929a13b0817cb62789410b3e9a673523c6fdfd8a164626830d636f04aacc973a65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
